services:
#    feniu_frontend.example:
#        class: Feniu\FrontendBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

   layout_extension:
    class: Feniu\FrontendBundle\Twig\LayoutExtension
    arguments: [@service_container]
    tags:
        - { name: twig.extension }